# 06. Funciones principales de Pandas
- Con la función info puedo obtener un resumen de como esta compuesto mi dataset, es una buena idea iniciar con está función al analisar nuestros datos
- Con la función describe puedo saber cierta información estadística, solamente de nuestros datos numéricos. Esto es muy usado en la ciencia de datos
- La función head me retorna los primeros registros que yo especifique y la función tail me retorna los ultimos registros que yo especifique
- Con la función memory_usage junto con el parametro deep=True, puedo saber cuanta memoria estoy usando en mis DataFrame
- Con la función value_counts y especificando mi objeto, puedo contar los valores que existen de ese objeto
- Con la función drop_duplicates puedo eliminar los duplicados que se encuentran en mi dataset
- Con la función sort_values puedo organizar mis datos ascendentemente o descendentemente según la columna que yo especifique
- Existen muchas funciones que es importante practicar

## Importar librería

In [1]:
import pandas as pd

## Cargar DataFrame

In [2]:
df_books = pd.read_csv('./bd/bestsellers-with-categories.csv',sep=',',header=0)
df_books.head(2) # Mostrar las primeras dos lineas de registro

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

## info()

In [3]:
df_books.info() # Mostrar los diferentes datos que contiene el dataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

## describe()

In [ ]:
df_books.describe() # Obtener diferentes datos estadisticos de las columnas numericas.

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

## head() y tail()

In [6]:
df_books.tail(5) # Mostrar los últimos 5 registros del dataFrame

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [7]:
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

## memory_usage()

In [ ]:
df_books.memory_usage(deep=True) # Obtener el uso de la memoria de cada columna

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

## value_counts()

In [ ]:
df_books['Author'].value_counts() # Cuenta cuantos valores tengo por cada uno de los autores

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

## drop_duplicates()

In [ ]:
df_books.iloc[0] # Obtener la informacion de un registro especifico

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [ ]:
df_books = df_books.append(df_books.iloc[0]) # Se usa para incrementar el dataframe

In [ ]:
df_books.drop_duplicates() # Eliminar registros duplicados

In [ ]:
df_books.drop_duplicates(keep='last') # Elimina el primer registro duplicado del dataFrame (orden ascendente)

                                                  Name  ...        Genre
1                                    11/22/63: A Novel  ...      Fiction
2              12 Rules for Life: An Antidote to Chaos  ...  Non Fiction
3                               1984 (Signet Classics)  ...      Fiction
4    5,000 Awesome Facts (About Everything!) (Natio...  ...  Non Fiction
5        A Dance with Dragons (A Song of Ice and Fire)  ...      Fiction
..                                                 ...  ...          ...
546  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction
547  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction
548  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction
549  You Are a Badass: How to Stop Doubting Your Gr...  ...  Non Fiction
0                        10-Day Green Smoothie Cleanse  ...  Non Fiction

[550 rows x 7 columns]

## sort_values()

In [9]:
df_books.sort_values('Year') # Ordena los valores de menor a mayor segun el año (orden ascendente)

,Name,Author,User Rating,Reviews,Price,Year,Genre
177,"I, Alex Cross",James Patterson,4.6,1320,7,2009,Fiction
131,Glenn Beck's Common Sense: The Case Against an...,Glenn Beck,4.6,1365,11,2009,Non Fiction
417,The Last Lecture,Randy Pausch,4.7,4028,9,2009,Non Fiction
241,New Moon (The Twilight Saga),Stephenie Meyer,4.6,5680,10,2009,Fiction
72,Diary of a Wimpy Kid: The Last Straw (Book 3),Jeff Kinney,4.8,3837,15,2009,Fiction
...,...,...,...,...,...,...,...
150,Guts,Raina Telgemeier,4.8,5476,7,2019,Non Fiction
466,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.6,26490,15,2019,Non Fiction
462,The Silent Patient,Alex Michaelides,4.5,27536,14,2019,Fiction
130,"Girl, Wash Your Face: Stop Believing the Lies ...",Rachel Hollis,4.6,22288,12,2019,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [8]:
df_books.sort_values('Year',ascending=False) # Ordenar los registros segun valores de la columna (orden desendiente)

,Name,Author,User Rating,Reviews,Price,Year,Genre
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction
294,School Zone - Big Preschool Workbook - Ages 4 ...,School Zone,4.8,23047,6,2019,Non Fiction
489,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842,10,2019,Fiction
263,P is for Potty! (Sesame Street) (Lift-the-Flap),Naomi Kleinberg,4.7,10820,5,2019,Non Fiction
130,"Girl, Wash Your Face: Stop Believing the Lies ...",Rachel Hollis,4.6,22288,12,2019,Non Fiction
...,...,...,...,...,...,...,...
418,The Last Olympian (Percy Jackson and the Olymp...,Rick Riordan,4.8,4628,7,2009,Fiction
38,"Breaking Dawn (The Twilight Saga, Book 4)",Stephenie Meyer,4.6,9769,13,2009,Fiction
92,"Eat This, Not That! Thousands of Simple Food S...",David Zinczenko,4.3,956,14,2009,Non Fiction
139,Good to Great: Why Some Companies Make the Lea...,Jim Collins,4.5,3457,14,2009,Non Fiction
299,Sookie Stackhouse,Charlaine Harris,4.7,973,25,2009,Fiction

## Recursos adicionales
[10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)